spring.application.name=pescd

spring.datasource.url=jdbc:mysql://localhost:3306/db_pescd?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# update caso queira salvar o bd
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# AL.02/AL.03/AL.04: configurações de upload de arquivos
# Tamanho máximo do arquivo individual (RN-3 de AL.02, AL.03 e AL.04)
spring.servlet.multipart.max-file-size=5MB
# Tamanho máximo da requisição inteira (arquivo + campos do formulário)
spring.servlet.multipart.max-request-size=6MB
